import zipfile, xml.dom.minidom as M, re, os
HERE = os.path.dirname(os.path.abspath(__file__))
z = zipfile.ZipFile(os.path.join(HERE, "PerfDiag.xlam"))
names = z.namelist()
print("customUI part present:", "customUI/customUI14.xml" in names)
rels = z.read("_rels/.rels").decode()
print("relationship present:", "customUI/customUI14.xml" in rels)
ui = z.read("customUI/customUI14.xml").decode()
M.parseString(ui)
print("customUI XML well-formed: True")
acts = set(re.findall(r'onAction="([^"]+)"', ui)) | set(re.findall(r'onLoad="([^"]+)"', ui))
print("callbacks referenced:", sorted(acts))
rib = open(os.path.join(HERE, "modRibbon.bas"), encoding="utf-8").read()
print("all callbacks defined in modRibbon:", all(("Sub " + a) in rib for a in acts))
print("vbaProject.bin present:", "xl/vbaProject.bin" in names)
